### ISSUE TITLE
Modals are not very mobile-friendly

### ISSUE THREAD

**Issue by ThinkGraphical** [yuanyan/boron#10]
With a fixed width of 500px, the modals aren't very mobile-friendly.

I've resolved this by adding a selector to the 'modal-body'
and overwritten it with `width: 90% !important;` as a default.
On desktop-viewport added the `width: 500px !important;`.

Even though it's really easy to do this yourself,
it would be nice if the modals are more mobile-friendly by default.

**Comment by yuanyan** [comment]
yeah, in my todo list, and pull request welcome!
