### ISSUE TITLE
Invalid prop keyboard of type function supplied to Constructor

### ISSUE THREAD

**Issue by SuperManEver** [yuanyan/boron#30]
When I try to provide callback for handling escape key press using `keyboard` I get back warning complaing about `Failed prop type`. I tried to use `onKeyPress`, but none of the approaches work as expected, function that I provided as callback doesn't get called.

`<Modal ref="modal" keyboard={this.callback}>
  <h2>Edit Modal</h2>
  <button onClick={this.hideModal}>Close</button>
</Modal>`

**Comment by ViniciusTavares** [comment]
It still doesn't work... I've been using a boolean to skip this warning.
