### ISSUE TITLE
Inline styling doesn't allow custom styles

### ISSUE THREAD

**Issue by zackify** [yuanyan/boron#7]
So we're trying to change the styling on boron's drop modal. The problem is, this: https://github.com/yuanyan/boron/blob/master/src/DropModal.js#L92 is forcing certain styles that cannot be overwrriten by a classname. I really want to be able to change the background color at least. Any ideas? I'd be interested in helping out with this.

**Comment by interator** [comment]
Is there a way to change the style of the Modal, when you displays the modal in a mobile device the modal width is bigger than the window width.

**Comment by zackify** [comment]
I made my own for now, you can completely change anything.
http://github.com/zackify/simple-react-modal would love to see this one
have custom styles.
